apiVersion: v1
data:
  application.properties: |
    # Kafka Bootstrap Servers
    kafka.bootstrap-servers=my-cluster-kafka-brokers.kafka.svc:9092
    # Topics
    kafka.topic = mymessages
    kafka.message = "ceci est un test"
kind: ConfigMap
metadata:
  name: appconfig
  namespace: kamel-demo
