apiVersion: v1
kind: Secret
metadata:
  name: my-datasource
stringData:
  datasource.properties: |-
     quarkus.datasource.camel.jdbc.url=jdbc:mysql://messagedb:3306/messagedb
     quarkus.datasource.camel.username=messagedb
     quarkus.datasource.camel.password=Demo1234
     quarkus.datasource.camel.db-kind=mysql
